description: >
  Allows the kubectl client to work with a GKE cluster.
  Updates the kubectl configuration file with GKE cluster access credentials.

parameters:
  cluster:
    description: >
      The name of the cluster for which to create a kubeconfig entry.
    type: string
  perform-login:
    description: >
      Whether to perform a login with the gcloud CLI.
    type: boolean
    default: false
  gcloud-service-key:
    description: The gcloud service key
    type: env_var_name
    default: GCLOUD_SERVICE_KEY
  google-project-id:
    description: The Google project ID to connect with via the gcloud CLI
    type: env_var_name
    default: GOOGLE_PROJECT_ID
  google-compute-zone:
    description: The Google compute zone to connect with via the gcloud CLI
    type: env_var_name
    default: GOOGLE_COMPUTE_ZONE
  google-compute-region:
    description: The Google compute region to connect with via the gcloud CLI
    type: env_var_name
    default: GOOGLE_COMPUTE_REGION
  install-kubectl:
    description: >
      Whether to install kubectl
    type: boolean
    default: false

steps:
  - gcloud/install
  - when:
      condition: <<parameters.perform-login>>
      steps:
        - gcloud/initialize:
            gcloud-service-key: <<parameters.gcloud-service-key>>
            google-project-id: <<parameters.google-project-id>>
            google-compute-zone: <<parameters.google-compute-zone>>
            google-compute-region: <<parameters.google-compute-region>>
  - when:
      condition: <<parameters.install-kubectl>>
      steps:
        - k8s/install-kubectl
  - run:
      name: Update kubeconfig with cluster credentials
      command: |
        gcloud container clusters get-credentials <<parameters.cluster>>
