description: >
  Allows the kubectl client to work with a GKE cluster.
  Updates the kubectl configuration file with GKE cluster access credentials.

parameters:
  cluster:
    description: >
      The name of the cluster for which to create a kubeconfig entry.
    type: string
  additional_args:
    description: Additional arguments to "gcloud container clusters get-credentials"
    type: string
    default: ""
  use_gke_cloud_auth_plugin:
    description: >
      If true, use the gke-gcloud-auth-plugin to authenticate with the cluster.
      See more at: https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
    type: boolean
    default: true

steps:
  - run:
      name: Update kubeconfig with cluster credentials
      environment:
        ORB_EVAL_CLUSTER: <<parameters.cluster>>
        ORB_EVAL_ADDITIONAL_ARGS: <<parameters.additional_args>>
        ORB_VAL_USE_GKE_GCLOUD_AUTH_PLUGIN: <<parameters.use_gke_cloud_auth_plugin>>
        ORB_SCRIPT_UTILS: <<include(scripts/utils.sh)>>
      command: <<include(scripts/update-kubeconfig-with-credentials.sh)>>
